# Generated by Django 4.2.17 on 2024-12-13 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='is_feature',
            new_name='is_featured',
        ),
    ]
